Void-Crew/Voidcrew-LRP

_maps/RandomRuins/SpaceRuins/nanotrasen_office.dmm
_maps/configs/KOS_crescent.json
_maps/configs/KOS_greenpill.json
_maps/configs/KOS_lamia.json
_maps/configs/KOS_merlin.json
_maps/configs/KOS_roguemalf.json
_maps/configs/NEU_Homestead.json
_maps/configs/NEU_prometheus.json
_maps/configs/NT-C_clipper.json
_maps/shuttles/shiptest/NEU_prometheus.dmm
_maps/shuttles/shiptest/cricket.dmm
_maps/shuttles/shiptest/lamia.dmm
_maps/shuttles/shiptest/voidcrew/Homestead.dmm
_maps/shuttles/shiptest/voidcrew/Roguemalf.dmm
_maps/shuttles/shiptest/voidcrew/crescent.dmm
_maps/shuttles/shiptest/voidcrew/greenpill.dmm
_maps/shuttles/shiptest/voidcrew/merlin.dmm
_maps/shuttles/shiptest/voidcrew/nanotrasen_clipper.dmm
code/game/objects/items/survery_handheld.dm
config/ruins/spaceruinblacklist.txt
voidcrew/code/game/area/ship_areas.dm
voidcrew/code/modules/jobs/job_types/assistant.dm
voidcrew/code/modules/jobs/job_types/captain.dm
voidcrew/code/modules/jobs/job_types/head_of_personnel.dm
voidcrew/code/modules/jobs/job_types/medical_doctor.dm
voidcrew/code/modules/jobs/job_types/security_officer.dm
voidcrew/code/modules/overmap/ships/simulated.dm

https://github.com/Acensti/Voidcrew-LRP/pull/15/
This also fixes a reported survey handheld issue according to the contributer

All of my ships from voidcrew reupload

---

_maps/configs/NEU_afflictor.json
_maps/shuttles/shiptest/voidcrew/afflictor.dmm

https://github.com/Acensti/Voidcrew-LRP/pull/3

Adds the afflictor class phase frigate

---

_maps/configs/NEU_Frankenstein.json
_maps/shuttles/shiptest/voidcrew/Frankenstein.dmm

https://github.com/Acensti/Voidcrew-LRP/pull/14

Frankenstein Ship

---

_maps/configs/NEU_atmosia.json
_maps/shuttles/shiptest/voidcrew/atmosia.dmm

https://github.com/Acensti/Voidcrew-LRP/pull/18

Atmosian Ship

---

_maps/configs/SYN-C_voidcrawler.json
_maps/shuttles/shiptest/voidcrew/voidcrawler.dmm

https://github.com/Acensti/Voidcrew-LRP/pull/20

Syndimos ship

---

code/__HELPERS/qdel.dm
code/_onclick/drag_drop.dm
code/controllers/subsystem/icon_smooth.dm
code/datums/hud.dm
code/datums/mind.dm
code/datums/traits/_quirk.dm
code/game/objects/objs.dm
code/game/turfs/turf.dm
code/modules/admin/view_variables/reference_tracking.dm
code/modules/flufftext/Dreaming.dm
code/modules/mob/living/carbon/carbon_defines.dm
code/modules/mob/living/living.dm
code/modules/mob/living/simple_animal/bot/bot.dm
code/modules/mob/mob.dm

* Fix a hanging reference to cables
* Fix more hanging references
* Tweak find_references for better debugging
* Optimise hud removal loop
* Improve QDEL_IN argument naming
Co-authored-by: MarinaGryphon <jadebishop2562@gmail.com>
:cl:
code: fixes hanging references
/:cl:

[UPSTREAM]Fix more hanging references (#844)

---

code/modules/admin/view_variables/reference_tracking.dm
code/modules/mob/dead/observer/observer.dm

https://github.com/shiptest-ss13/Shiptest/pull/837

[UPSTREAM] Fix three hanging references to mobs #837

---

code/datums/mind.dm

https://github.com/shiptest-ss13/Shiptest/pull/853

[UPSTREAM] Hotfix for new_player failing to GC on observe.

---

_maps/templates/shelter_3.dmm

What it says on the tin.
It's a bar, no reason it can't come with a bartender
:cl:
add: Added a bar holopad to the bar emergency shelter
/:cl:

Adds a bar holpad to the bar emergency shelter

---

code/modules/admin/verbs/adminhelp.dm

https://github.com/tgstation/tgstation/pull/64875
This PR, on TG, fixed a weird issue we've been having. This should allow us to properly use the DB.
To go into more detail, the ticket field is meant to be a smallint, but was being passed as a string in this proc, the full name of the ticket as displayed in-game. For those who don't know, this is the full first message sent as the original ahelp, trimmed to a certain length.
DB working is good.
:cl:
fix: fixed database logging of tickets when clients disconnect
/:cl:

Fixes a database issue with clients 

---

_maps/shuttles/shiptest/statio.dmm

After playing a recent round on the statio, I noticed a couple weird issues with statio.
Moves the surgery bags out of the back room and into the surgery room
Fixes a few decals in sec that I didn't squash way back when
Moves some areas to be on the "proper" side of some walls
Removes the defibs from the surgery room and replaces the defib mounts with loaded defib mounts. This was a miniscule amount of busywork that is wholly unnecessary. 
Not having to search for surgery duffel bags UNDER a defib sprite is helpful
:cl:
tweak: A few minor things in statio medical have been adjusted
/:cl:

Touches up statio medical

---

code/game/alternate_appearance.dm

Fixes runtime in cult

---

code/modules/hydroponics/plant_genes.dm
voidcrew/code/modules/shuttle/emergency.dm

cell runtime fix

---

code/__HELPERS/_lists.dm
code/controllers/subsystem/parallax.dm
code/controllers/subsystem/sounds.dm
code/controllers/subsystem/timer.dm
code/datums/action.dm
code/datums/weather/weather.dm
code/game/alternate_appearance.dm
code/game/atoms_movable.dm
code/game/machinery/computer/launchpad_control.dm
code/game/objects/items/storage/wallets.dm
code/modules/admin/chat_commands.dm
code/modules/atmospherics/environmental/LINDA_system.dm
code/modules/client/client_procs.dm
code/modules/detectivework/scanner.dm
code/modules/mob/dead/observer/logout.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
code/modules/mob/logout.dm
code/modules/tgui/tgui.dm
code/modules/vehicles/vehicle_actions.dm

Co-authored-by: MarinaGryphon <jadebishop2562@gmail.com>
https://github.com/shiptest-ss13/Shiptest/pull/833

[UPSTREAM] Fix many erroneous lazylist macro uses

---

code/controllers/subsystem/explosions.dm

explosion runtime fix

---

code/__DEFINES/MC.dm
code/__DEFINES/_tick.dm
code/__DEFINES/qdel.dm
code/__DEFINES/time.dm
code/__DEFINES/vv.dm
code/__HELPERS/qdel.dm
code/__HELPERS/unsorted.dm
code/controllers/configuration/entries/game_options.dm
code/controllers/configuration/entries/general.dm
code/controllers/master.dm
code/controllers/subsystem.dm
code/controllers/subsystem/garbage.dm
code/controllers/subsystem/input.dm
code/controllers/subsystem/profiler.dm
code/controllers/subsystem/server_maint.dm
code/controllers/subsystem/statpanel.dm
code/controllers/subsystem/title.dm
code/controllers/subsystem/vote.dm
code/datums/weakrefs.dm
code/modules/tgchat/to_chat.dm
config/config.txt

https://github.com/shiptest-ss13/Shiptest/pull/1424
https://github.com/shiptest-ss13/Shiptest/pull/1005

[UPSTREAM] "port" SSgarbage from /TG/, Ports MC initialization refactor

---

code/modules/clothing/spacesuits/miscellaneous.dm

This gives NT a fair chance to fight syndicate in space.
:cl:
add: ERT Hardsuits now start with a jetpack.
/:cl:

ERT Hardsuit jetpack

---

code/__DEFINES/misc.dm
code/__HELPERS/_logging.dm
code/__HELPERS/unsorted.dm
code/controllers/subsystem/npcpool.dm
code/datums/components/gps.dm
code/datums/components/orbiter.dm
code/datums/components/overlay_lighting.dm
code/datums/components/riding.dm
code/game/machinery/constructable_frame.dm
code/game/machinery/hologram.dm
code/modules/admin/IsBanned.dm
code/modules/admin/admin.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/ipintel.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/admin/view_variables/topic.dm
code/modules/cargo/expressconsole.dm
code/modules/economy/account.dm
code/modules/keybindings/bindings_client.dm
code/modules/keybindings/setup.dm
code/modules/paperwork/faxmachine.dm
interface/stylesheet.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss
voidcrew/code/controllers/subsystem/overmap.dm
voidcrew/code/game/machinery/shuttle/shuttle_engine_types.dm
voidcrew/code/modules/research/nanites/nanite_programs/utility.dm
whitesands/code/modules/antagonists/borer/borer.dm

Co-authored-by: Mark Suckerberg <mark@suckerberg.ga>
Co-authored-by: Mark Suckerberg <29362068+MarkSuckerberg@users.noreply.github.com>
port but without the economics and mining change, should cut more runtimes

[UPSTREAM] Attempt to chase down various runtimes, Grants R_DEBUG log access

---

_maps/shuttles/shiptest/voidcrew/indisputable.dmm

Seriously guys stop fucking putting these on ships.

Removes bar tables from the indisputable

---

_maps/shuttles/shiptest/voidcrew/libertarian.dmm

Patches a hole in the libertarian

---

code/modules/recycling/disposal/pipe.dm

Fixes the ability to dupe metal with disposals.

Patches a material duplication exploit

---

_maps/configs/KOS_greenpill.json

fixes greenpill being unspawnable

greenpill spawn fix

---

_maps/shuttles/shiptest/NEU_prometheus.dmm

Removes an /obj
Yes there was an /obj on the map.
Also moves cameras around to not be sharing a wall with lights, because that is weird.
Adds some emergency holopads.

Fixes up some oddities on the prometheus, adds holopads.

---

_maps/shuttles/shiptest/box.dmm
_maps/shuttles/shiptest/boyardee.dmm
_maps/shuttles/shiptest/delta.dmm

Squashed decals, added plumbing constructors to box and delta, swapped all the bulb-less light fixtures in the box to make it less shit.

Touches up box, boyardee, and delta

---

_maps/map_files/generic/CentCom.dmm
_maps/shuttles/escape_pod/escape_pod_large.dmm
_maps/shuttles/hunter/hunter_space_cop.dmm
_maps/shuttles/ruin/ruin_solgov_exploration_pod.dmm
_maps/shuttles/shiptest/liberty.dmm
_maps/shuttles/shiptest/rigoureux.dmm
_maps/shuttles/shiptest/rigoureux_d.dmm
_maps/shuttles/shiptest/scrapper_b.dmm
_maps/shuttles/shiptest/voidcrew/Nanopill.dmm
_maps/shuttles/shiptest/voidcrew/brilliant.dmm
_maps/shuttles/shiptest/voidcrew/libertarian.dmm
_maps/shuttles/shiptest/voidcrew/nooper.dmm
_maps/shuttles/shiptest/voidcrew/phalanx.dmm
_maps/shuttles/shiptest/voidcrew/thunderbird.dmm
_maps/shuttles/shiptest/voidcrew/trambullet.dmm
code/__DEFINES/icon_smoothing.dm
code/game/objects/effects/spawners/structure.dm
code/game/objects/items/stacks/sheets/glass.dm
code/game/objects/structures/grille.dm
code/game/objects/structures/window.dm
code/modules/mining/equipment/survival_pod.dm
voidcrew/_maps/RandomRuins/WastelandRuins/wasteland_clowncrash.dmm
voidcrew/_maps/RandomRuins/WastelandRuins/wasteland_surface_solgovcrash.dmm
voidcrew/_maps/RandomRuins/WastelandRuins/wasteland_tradepost.dmm

Reverts Void-Crew/Voidcrew-LRP#62

Revert "Makes shuttle windows deconstructible"

---

code/modules/shuttle/shuttle_rotate.dm

Makes SM setups possible without breaking every time the ship docks/undocks.
:cl:
fix: Reflectors now rotate correctly together with the ship.
/:cl:

[UPSTREAM] Fixes reflector rotation by shuttles

---

_maps/shuttles/shiptest/talos.dmm

revenge of the TEG
storage room stripped down, but!
SCIENCE!
we also stole back the commander pistols
I BROUGHT THIS SCUFFED MESS IN AND I CAN BRING THE SCUFF BACK OUT
:cl:
add: The NEU Talos has been sent back to the IRMG shipyards by the wrath of Voidcrew, and returned with its TEG intact and not replaced with a stopgap AME! also some extra touchups
/:cl:

Talos Descuffed

---

voidcrew/code/game/objects/items/storage/ammo_printer.dm

Fixes the ruin ammo printer
:cl:
fix: The ruin ammo printer doesn't require power anymore.
/:cl:

Fixes the ruin ammo printer

---

_maps/shuttles/shiptest/scrapper.dmm

:cl:
add: Adds a missing autolathe to the Scrapper ship.
/:cl:

Adds an autolathe to the Scrapper

---

code/modules/research/designs/tool_designs.dm
voidcrew/code/game/objects/items/shuttle_creator.dm
voidcrew/code/modules/overmap/helm.dm
voidcrew/code/modules/overmap/ships/simulated.dm
voidcrew/code/modules/research/techweb/all_nodes.dm

Readds the ship creator into R&D, and makes it work again
:cl:
fix: The ship creation tool is available again.
/:cl:

Shuttle creator fix

---

code/modules/mob/mob.dm

No idea if it works, 100% untested
:cl:
fix: Fixes very long respawn timers
/:cl:

Respawn timer fix

---

code/modules/client/client_defines.dm
code/modules/client/verbs/ooc.dm

:cl:
add: Allows players to enable fullscreen.
/:cl:

Toggle Fullscreen

---

_maps/shuttles/shiptest/voidcrew/thunderbird.dmm

Fixes the Thunderbird map being completely broken.
:cl:
/:cl:

Thunderbird fix
